### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by WifiRouterYT** [Zer0Mem0ry/ScreenMelter#2]
Upon compiling, I get this:
`1>------ Build started: Project: ScreenMelter, Configuration: Debug x64 ------
1>main.cpp
1>MSVCRTD.lib(exe_main.obj) : error LNK2019: unresolved external symbol main referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ)
1>C:\Users\Ivan\Desktop\ScreenMelter\x64\Debug\ScreenMelter.exe : fatal error LNK1120: 1 unresolved externals
1>Done building project "ScreenMelter.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========`

I am new to coding, so I cannot resolve this issue on my own.
Info: 
**Visual Studio 2019 Professional (trial)
Intel i3 8145U CPU @ 2.30 GHz max
20 GB RAM (19.8 GB usable)
Windows 10 Home
Touch support with 10 touch points**
PC: Lenovo IdeaPad S340-Touch

**Comment by isira-adithya** [comment]
I got that error too
![image](https://user-images.githubusercontent.com/65585354/95168351-cc77e900-07ce-11eb-905c-04ea53e897f1.png)
I am using Visual Studio 2019

**Comment by isira-adithya** [comment]
I fixed It using 
![image](https://user-images.githubusercontent.com/65585354/95169072-ebc34600-07cf-11eb-8b26-a4b58d876bdf.png)
Propertice of the Project --> Linker --> System --> Subsystem = Windows
It worked!

**Comment by WifiRouterYT** [comment]
Awesome! Thanks for the help!
